### ISSUE TITLE
Bug: startpage engine

### ISSUE THREAD

**Issue by Kron00** [searxng/searxng#1857]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2022.05.11-459b9c18

**How did you install SearXNG?**

**What happened?**

**How To Reproduce**

**Expected behavior**

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: TypeError
  * Percentage: 100
  * Parameters: `('SearxEngineResponseException() takes no keyword arguments',)`
  * File name: `searx/engines/startpage.py:96`
  * Function: `get_sc_code`
  * Code: `raise SearxEngineResponseException(`

**Comment by dalf** [comment]
With the #1860, the issue should be fixed (last commit on the master branch : 1a5b096 )

**Comment by nicfab** [comment]
> With the #1860, the issue should be fixed (last commit on the master branch : [1a5b096](https://github.com/searxng/searxng/commit/1a5b0965789d100a33fad69cf6779b23e6595ef4) )

I have the SearXNG version 2022.10.14-1a5b0965, and I still have the issue unless the updated version has yet to be released.

**Comment by dalf** [comment]
Do you see `2022.10.14-1a5b0965` at the bottom of the pages?

**Comment by nicfab** [comment]
> Do you see `2022.10.14-1a5b0965` at the bottom of the pages?

Yes
