### ISSUE TITLE
Something brokes SearXNG search api when i choose json format and videos category

### ISSUE THREAD

**Issue by mbaroncini** [searxng/searxng#2505]
**Version:**
2023.6.16+71b6ff07 
docker image: searxng/searxng:latest

**What happened?**
When i try `http://localhost:8080/search?q=test&format=csv&categories=videos` this works both on chromium broswer and via terminal using curl :`curl "http://localhost:8080/search?q=test&format=csv&categories=videos"`

This instead works only on browser: `http://localhost:8080/search?q=test&format=json&categories=videos`, when i try on terminal `curl "http://localhost:8080/search?q=test&format=json&categories=videos"` i obtain 
```
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

**How To Reproduce**
Run searxng with docker:

```
mkdir test
docker pull searxng/searxng
docker run -d --rm \
              -d -p 8080:8080 \
              --name searxng_test \
              -v "./test:/etc/searxng" \
              -e "BASE_URL=http://localhost:8080/" \
              searxng/searxng
```

update formats on test/settings.yml

```
  # formats: [html, csv, json, rss]
  formats:
    - html
    - json
    - csv
```
restart the docker container:

```
docker restart searxng_test
```

Now if you try to query the search api with `curl "http://localhost:8080/search?q=test&categories=videos&format=csv"` should be fine.

Instead : `curl "http://localhost:8080/search?q=test&categories=videos&format=json"` raises an error 500

**Expected behavior**
The json format should work as the csv does.

**Screenshots & Logs**
These are the docker container logs:
```

searxng_  | DEBUG   searx.network.vimeo           : HTTP Request: GET https://vimeo.com//search/page:1?q=test "HTTP/1.1 200 OK" (text/html; charset=UTF-8)
searxng_  | DEBUG   searx.webapp                  : http%3A//localhost%3A8080/search%3Fq%3Dtest%26format%3Djson%26categories%3Dvideos uses locale `en`
searxng_  | ERROR   searx.webapp                  : Exception on /search [GET]
searxng_  | Traceback (most recent call last):
searxng_  |   File "/usr/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
searxng_  |     response = self.full_dispatch_request()
searxng_  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng_  |   File "/usr/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
searxng_  |     rv = self.handle_user_exception(e)
searxng_  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng_  |   File "/usr/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
searxng_  |     rv = self.dispatch_request()
searxng_  |          ^^^^^^^^^^^^^^^^^^^^^^^
searxng_  |   File "/usr/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
searxng_  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
searxng_  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng_  |   File "/usr/local/searxng/searx/webapp.py", line 764, in search
searxng_  |     response = json.dumps(x, default=lambda item: list(item) if isinstance(item, set) else item)
searxng_  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng_  |   File "/usr/lib/python3.11/json/__init__.py", line 238, in dumps
searxng_  |     **kw).encode(obj)
searxng_  |           ^^^^^^^^^^^
searxng_  |   File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
searxng_  |     chunks = self.iterencode(o, _one_shot=True)
searxng_  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng_  |   File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
searxng_  |     return _iterencode(o, 0)
searxng_  |            ^^^^^^^^^^^^^^^^^
searxng_  | ValueError: Circular reference detected
searxng_  | [pid: 10|app: 0|req: 5/19] 127.0.0.1 () {24 vars in 341 bytes} [Sat Jun 17 14:48:28 2023] GET /search?q=test&format=json&categories=videos => generated 265 bytes in 1657 msecs (HTTP/1.1 500) 9 headers in 766 bytes (1 switches on core 1)

```

Any help will be appreciated :) 
Thanks!

**Comment by return42** [comment]
@mbaroncini thanks a lot for your bug report and the detailed analysis that was very helpful for me :+1:  .. I implemented a patch in 

- https://github.com/searxng/searxng/pull/2508

**Comment by mbaroncini** [comment]
Thanks @return42 !

**Comment by rc-sr** [comment]
I am still seeing this issue with **docker.io/searxng/searxng:latest**. RSS and CSV work fine, but JSON does not.

```
searxng  | 2025-01-29 00:59:01,513 ERROR:searx.webapp: Exception on /search [POST]
searxng  | Traceback (most recent call last):
searxng  |   File "/usr/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
searxng  |     response = self.full_dispatch_request()
searxng  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
searxng  |     rv = self.handle_user_exception(e)
searxng  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
searxng  |     rv = self.dispatch_request()
searxng  |          ^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
searxng  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
searxng  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/local/searxng/searx/webapp.py", line 666, in search
searxng  |     response = webutils.get_json_response(search_query, result_container)
searxng  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/local/searxng/searx/webutils.py", line 172, in get_json_response
searxng  |     response = json.dumps(x, cls=JSONEncoder)
searxng  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/json/__init__.py", line 238, in dumps
searxng  |     **kw).encode(obj)
searxng  |           ^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/json/encoder.py", line 200, in encode
searxng  |     chunks = self.iterencode(o, _one_shot=True)
searxng  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
searxng  |   File "/usr/lib/python3.12/json/encoder.py", line 258, in iterencode
searxng  |     return _iterencode(o, 0)
searxng  |            ^^^^^^^^^^^^^^^^^
searxng  | ValueError: Circular reference detected
searxng  | [pid: 21|app: 0|req: 5/14] 172.19.0.1 () {58 vars in 1148 bytes} [Wed Jan 29 00:59:00 2025] POST /search => generated 265 bytes in 823 msecs (HTTP/1.1 500) 8 headers in 581 bytes (1 switches on core 3)
```

**Comment by Strangahhh** [comment]
@squeakyrobot

I'm struck with the same issue about Json on my locally host

**Comment by return42** [comment]
> I am still seeing this issue with **docker.io/searxng/searxng:latest**. RSS and CSV work fine, but JSON does not.

Sure? .. I can't reproduce the issue any longer, with current master checked out I tested:

```diff
@@ -74,9 +74,9 @@ search:
     recaptcha_SearxEngineCaptcha: 604800
 
   # remove format to deny access, use lower case.
-  # formats: [html, csv, json, rss]
-  formats:
-    - html
+  formats: [html, csv, json, rss]
+  # formats:
+  #   - html
```

In one terminal:

    make run

and in another terminal:

    curl "http://localhost:8888/search?q=test&format=json" 

----

What engines are active .. can you give me some more hints please / thanks 👍

**Comment by return42** [comment]
TBH this is an old issue which has been fixed a while ago:

- https://github.com/searxng/searxng/pull/2508

But there was an (new) issue related to JSON theses days:

- https://github.com/searxng/searxng/issues/4244

and this (new) issue has also been fixed / in:

- https://github.com/searxng/searxng/pull/4248

**Comment by rc-sr** [comment]
@return42 
You are correct that I attached it to the wrong issue, the underlying error was the same but when looking at my stack trace:

```
searxng  |   File "/usr/local/searxng/searx/webutils.py", line 172, in get_json_response
searxng  |     response = json.dumps(x, cls=JSONEncoder)
searxng  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I see that the error is coming from a file that you added in your fix.

For what its worth I cloned the repo and cannot reproduce it when running from main. But it is still reproducible running the latest docker container: **docker.io/searxng/searxng:latest**

If I find any useful information I'll open a new issue

**UPDATE**: I built a docker container from main and used it in my system, with my config, and it works as well. @Strangahhh This may work for you for now

**Comment by realnedsanders** [comment]
@squeakyrobot I was also seeing this issue, but it appears to be fixed in `docker.io/searxng/searxng@sha256:083f9224b885177d98fee5b5f6d9030c8beae626aa1b43435225f41f4c4f0e87`

**Comment by Axodouble** [comment]
Yup, seemed to be running into this issue as well, but like @realnedsanders suggested that image seems to work fully fine, was pulling my hair out trying to solve it.

**Comment by Axodouble** [comment]
@return42 are you able to re-open this issue as it appears to be relevant again?

**Comment by return42** [comment]
> @return42 are you able to re-open this issue as it appears to be relevant again?

This issue is OLD (!2023!) .. the issue you all are looking for is:

> - https://github.com/searxng/searxng/issues/4244
>
> and this (new) issue has also been fixed / in:
> 
> - https://github.com/searxng/searxng/pull/4248

this fix has been merged 12h ago .. and the new docker build (11h ago) from https://hub.docker.com/r/searxng/searxng include the patch .. please update your docker images.

Read: these two comments: https://github.com/searxng/searxng/issues/2505#issuecomment-2620743942 and https://github.com/searxng/searxng/issues/2505#issuecomment-2620758418

**Comment by rc-sr** [comment]
> [@squeakyrobot](https://github.com/squeakyrobot) I was also seeing this issue, but it appears to be fixed in `docker.io/searxng/searxng@sha256:083f9224b885177d98fee5b5f6d9030c8beae626aa1b43435225f41f4c4f0e87`

@realnedsanders 
Yep, that works for me. I tried the previous versions and it looks like this was fixed with `searxng/searxng:2025.1.29-a235c54f8`  and but the one prior (`searxng/searxng:2025.1.28-906b9e7d4`) has the issue.

I just pulled the latest `searxng/searxng:latest` :) and its working fine.
