### ISSUE TITLE
Bug: mojeek engine

### ISSUE THREAD

**Issue by cameronj86** [searxng/searxng#4307]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2025.2.3+4ab7984ed+dirty

**How did you install SearXNG?**
Docker, but it is happening across various public instances as well
**What happened?**
Errors out

**How To Reproduce**
`!mjk test`

**Expected behavior**
Results

**Additional context**
I also tried the following:
* Visiting mojeek directly to make sure my IP wasn't blocked
* Visiting public instances to make sure that it was widespread
* Selecting instances that don't use ipv6 (as per https://github.com/searxng/searxng/discussions/3188) to confirm that the issue is unrelated
* Changed `outgoing:   source_ips: 0.0.0.0` in my `settings.yml` file to make sure ipv6 wasn't the issue on my end.

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 100
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:116`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by jj-code-00** [comment]
Having the same issue.

**Comment by shinodark** [comment]
It seems to me that "&fmt=" argument in generated url by searxng triggers an automated tools detection from mojeek

log from searxng with http 403 triggered : 
 WARNING:searx.network.mojeek: HTTP Request failed: GET https://www.mojeek.com/search?q=searxng&safe=0&fmt=&lb=fr&arc=fr&s=0

With manually removed fmt arg it seems ok :
https://www.mojeek.com/search?q=searxng&safe=0&lb=fr&arc=fr&s=0

**Comment by return42** [comment]
@shinodark thanks a lot for pointing out 👍 .. today I merged https://github.com/searxng/searxng/pull/4354 to fix the issue.

**Comment by elvisisvan** [comment]
still happening in version `2025.2.20+28d1240fc` on multiple instances (tested on https://search.ononoki.org and https://opnxng.com)
![Image](https://github.com/user-attachments/assets/af3a861e-17ae-4844-989a-9bacca92a9a6)

**Comment by cameronj86** [comment]
`2025.2.20+caf0dd537` is working as expected w/ my self-hosted version. The public instances on searx.space have moved beyond this commit so I can't test publicly, but perhaps something in the more recent commits are playing a role here.

**Comment by return42** [comment]
PR #4354 fixed https://github.com/searxng/searxng/issues/4307#issuecomment-2669355322 .. and with [Answer CAPTCHA from server’s IP](https://docs.searxng.org/admin/answer-captcha.html#answer-captcha-from-server-s-ip) mojeek can be unblocked for a while .. So a bug has been fixed, but the CAPTCHA problem is not completely solved:

![Image](https://github.com/user-attachments/assets/b9bf6a70-42d2-496f-a641-d021a2b38574)

**Comment by return42** [comment]
I haven't tested it, so I don't know if it works at all, but it might be worth taking a look at this project to improve our mojeek engine ..

- https://github.com/neon-mmd/websurfx/blob/rolling/src/engines/mojeek.rs

**Comment by ghost** [comment]
On the latest version I have the same 'access denied` message shown:

```
Response time: 1.0 seconds
mojeek	access denied
duckduckgo	1.0 
startpage	0.6 
brave	    0.5
```

4get also allows searches with mojeek in case it could be useful: https://git.lolcat.ca/lolcat/4get

**Comment by cameronj86** [comment]
This has stopped working for me again. Not sure if it was recent or just more noticeable now that other engines are also broken and so my results quality is diminishing.

**Edit**: Lol @ framed as low-quality. Anyways I figured it out. My split-tunneling wasn't working, so my VPS IP was being used. It's low-reputation and blocked by default. Re-enabling my split-tunneling resolved my engine-related issues

**Comment by jlacour-git** [comment]
Still reproducible on `2026.9.4+15b0c8ef3` (Docker, self-hosted, residential IPv4).
`!mjk <query>` returns no results, engine reports HTTP 403.

I spent some time isolating this, and I think the conclusion is that it is not a bug we can fix.

**It is not the request shape.** Replaying the URL that `mojeek.request()` builds
(`https://www.mojeek.com/search?q=<query>&safe=0`) from inside the container, using `httpx`
from SearXNG's own venv, returns 200 with a normal result page. Adding SearXNG's outgoing
headers (`Cache-Control: no-cache`, `DNT`, `Connection`, `Accept-Language`) makes no
difference. Ten alternating pairs, 3 s apart:

```
with Cache-Control + Connection:   5x 200, 5x 403
without both:                      5x 200, 5x 403
```

**It is a per-IP request budget.** After ~4 minutes of no traffic, a burst of one request per
second gave:

```
200 200 200 200 200 200 200 200 200 200 403 403
```

Ten through, then blocked. A fresh TCP connection does not reset it, so it is keyed on the
address, not the connection. An earlier burst with a partly-spent budget stopped after five.
Treat the exact figure as a lower bound rather than a constant: this is a single run, and I
had queried Mojeek several dozen times earlier the same day, so a fully rested budget may
well be larger. What is reproducible is the shape — a budget per address that refills.
This also explains why manual checks "always work": a single request after a quiet period is
always inside the budget — which is what everyone in this thread (myself included) was
measuring.

**And Mojeek's Terms of Service say this is intended.** Quoting
https://www.mojeek.com/about/terms.html :

> "use or access Our Services by any automated means (unless you are an authorised Mojeek API user)"

> "scraping the Services without Our prior consent is expressly prohibited"

> "crawling the Services is permissible if done in accordance with the provisions of the robots.txt file"

So the block is not a misconfiguration or an anti-bot false positive — automated non-API access
is prohibited by the operator, and they sell a Search API for exactly this purpose.

**Suggestion for maintainers:** this looks like a decision rather than a fix. Either the engine
becomes an API-key engine in the shape of `braveapi` (which already exists and documents
`api_key` as mandatory), or it gets marked `inactive: true` with a note pointing at the API, so
that operators do not keep re-filing this. Leaving it enabled means every search sends a
request that is refused most of the time and then suspends the engine for `suspended_times`.

I have disabled it locally and am not looking for a workaround — posting the measurement only
so the next person finds a cause instead of another header theory.
