### ISSUE TITLE
database locked / system halt

### ISSUE THREAD

**Issue by un99known99** [searxng/searxng#4984]
I faced 2-3 a total system freeze / mem full error causing system to halt.

Might it be related to 

  File "/usr/local/searxng/searxng-src/searx/cache.py", line 369, in set
    self.DB.execute(sql, (key, value, expire, value, expire))
sqlite3.OperationalError: database is locked

$ grep locked searXNG_error.log | wc -l
539

After disabling searXNG it seems to run fine again 

 NameError: name 'logger' is not defined
  163 2025-07-08 09:31:21,598 ERROR:searx.plugins.tracker_url_remover: Exception while calling on_result
  164 Traceback (most recent call last):
  165   File "/usr/local/searxng/searxng-src/searx/plugins/_core.py", line 270, in on_result
  166     ret = bool(plugin.on_result(request=request, search=search, result=result))
  167                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  168   File "/usr/local/searxng/searxng-src/searx/plugins/tracker_url_remover.py", line 42, in on_result
  169     result.filter_urls(self.filter_url_field)
  170   File "/usr/local/searxng/searxng-src/searx/result_types/_base.py", line 292, in filter_urls
  171     _filter_urls(self, filter_func=filter_func)
  172   File "/usr/local/searxng/searxng-src/searx/result_types/_base.py", line 127, in _filter_urls
  173     new_url = filter_func(result, field_name, url_src)
  174               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  175   File "/usr/local/searxng/searxng-src/searx/plugins/tracker_url_remover.py", line 54, in filter_url_field
  176     return TRACKER_PATTERNS.clean_url(url=url_src)
  177            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  178   File "/usr/local/searxng/searxng-src/searx/data/tracker_patterns.py", line 101, in clean_url
  179     for rule in self.rules():
  180   File "/usr/local/searxng/searxng-src/searx/data/tracker_patterns.py", line 68, in rules
  181     self.init()
  182   File "/usr/local/searxng/searxng-src/searx/data/tracker_patterns.py", line 45, in init
  183     self.load()
  184   File "/usr/local/searxng/searxng-src/searx/data/tracker_patterns.py", line 54, in load
  185     self.add(rule)
  186   File "/usr/local/searxng/searxng-src/searx/data/tracker_patterns.py", line 57, in add
  187     self.cache.set(
  188   File "/usr/local/searxng/searxng-src/searx/cache.py", line 369, in set
  189     self.DB.execute(sql, (key, value, expire, value, expire))

  **_190 sqlite3.OperationalError: database is locked_**

  191 /usr/local/searxng/searx-pyenv/lib/python3.11/site-packages/httpx/_models.py:408: DeprecationWarning: Use 'content=<...>' to upload raw bytes/text content.
  192   headers, stream = encode_request(
  193 2025-07-08 09:31:26,461 ERROR:searx.engines.ask: engine timeout
  194 2025-07-08 09:31:26,470 ERROR:searx.engines.bing: engine timeout
  195 2025-07-08 09:31:26,471 ERROR:searx.engines.ddg definitions: engine timeout
  196 2025-07-08 09:31:26,473 ERROR:searx.engines.wikidata: engine timeout
  197 2025-07-08 09:31:26,477 ERROR:searx.engines.duckduckgo: engine timeout
  198 2025-07-08 09:31:26,478 ERROR:searx.engines.google: engine timeout
  199 2025-07-08 09:31:26,479 ERROR:searx.engines.mwmbl: engine timeout
  200 2025-07-08 09:31:26,479 ERROR:searx.engines.mullvadleta: engine timeout
  201 2025-07-08 09:31:26,479 ERROR:searx.engines.mullvadleta brave: engine timeout
  202 2025-07-08 09:31:26,480 ERROR:searx.engines.presearch: engine timeout
  203 2025-07-08 09:31:26,480 ERROR:searx.engines.presearch videos: engine timeout
  204 2025-07-08 09:31:26,480 ERROR:searx.engines.right dao: engine timeout
  205 2025-07-08 09:31:26,480 ERROR:searx.engines.searchmysite: engine timeout
  206 2025-07-08 09:31:26,481 ERROR:searx.engines.startpage: engine timeout
  207 2025-07-08 09:31:26,481 ERROR:searx.engines.yahoo: engine timeout
  208 2025-07-08 09:31:26,483 ERROR:searx.engines.wiby: engine timeout
  209 2025-07-08 09:31:26,486 ERROR:searx.engines.wikibooks: engine timeout
  210 2025-07-08 09:31:26,493 ERROR:searx.engines.wikisource: engine timeout
  211 2025-07-08 09:31:26,510 ERROR:searx.engines.wikispecies: engine timeout
  212 2025-07-08 09:31:26,521 ERROR:searx.engines.wikiversity: engine timeout
  213 2025-07-08 09:31:26,522 ERROR:searx.engines.wikivoyage: engine timeout
  214 2025-07-08 09:31:26,522 ERROR:searx.engines.stract: engine timeout
  215 2025-07-08 09:31:26,522 ERROR:searx.engines.brave: engine timeou

**Comment by return42** [comment]
> I faced 2-3 a total system freeze / mem full error causing system to halt.

Please update instance .. 5min ago we merged a patch about the "mem full" .. 

- https://github.com/searxng/searxng/pull/4983

**Comment by un99known99** [comment]
@return42 

it is not fixed:

2025-07-08 11:54:06,860 ERROR:searx.plugins.tracker_url_remover: Exception while calling on_result
Traceback (most recent call last):
  File "/usr/local/searxng/searxng-src/searx/plugins/_core.py", line 270, in on_result
    ret = bool(plugin.on_result(request=request, search=search, result=result))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searxng-src/searx/plugins/tracker_url_remover.py", line 42, in on_result
    result.filter_urls(self.filter_url_field)
  File "/usr/local/searxng/searxng-src/searx/result_types/_base.py", line 292, in filter_urls
    _filter_urls(self, filter_func=filter_func)
  File "/usr/local/searxng/searxng-src/searx/result_types/_base.py", line 127, in _filter_urls
    new_url = filter_func(result, field_name, url_src)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searxng-src/searx/plugins/tracker_url_remover.py", line 54, in filter_url_field
    return TRACKER_PATTERNS.clean_url(url=url_src)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searxng-src/searx/data/tracker_patterns.py", line 101, in clean_url
    for rule in self.rules():
  File "/usr/local/searxng/searxng-src/searx/data/tracker_patterns.py", line 68, in rules
    self.init()
  File "/usr/local/searxng/searxng-src/searx/data/tracker_patterns.py", line 45, in init
    self.load()
  File "/usr/local/searxng/searxng-src/searx/data/tracker_patterns.py", line 54, in load
    self.add(rule)
  File "/usr/local/searxng/searxng-src/searx/data/tracker_patterns.py", line 57, in add
    self.cache.set(
  File "/usr/local/searxng/searxng-src/searx/cache.py", line 369, in set
    self.DB.execute(sql, (key, value, expire, value, expire))
sqlite3.OperationalError: database is locked

**Comment by return42** [comment]
> I faced 2-3 a total system freeze / mem full error causing system to halt.

The mem issue should be fixed / that the db is locked might have other reasons .. what setup do you have? .. do you use the docker image or is your installation done by the installation scripts? 

Try: stop your instance .. if you are using containers (docker or whatever) go into the container .. look out for the DB files in `/tmp`.. I have installed by the scripts (no docker) and in `/tmp` I found these DB files here:

```
$ ls -la /tmp/sxng_*
-rw-r--r-- 1 searxng searxng 24576 Jul  8 09:58 /tmp/sxng_cache_ENGINES_CACHE.db
```

**Comment by un99known99** [comment]
I do have installed via script.

Did a re-check:

found it:

-rw-r--r-- 1 searxng searxng 49152 Jul  8 12:23 /tmp/systemd-private-ce47039cadd14602b79b5f1bb5fdc78b-searXNG.service-2zTLmN/tmp/sxng_cache_ENGINES_CACHE.db

[/var/log] # tail -F searXNG_error.log | grep -i "database is locked"

seems no more entries.

Will monitor and feedback

**Comment by return42** [comment]
I suspect the DB table was still blocked by an SQL update that came from one of the dead processes (related to https://github.com/searxng/searxng/pull/4983). 

Upon reboot, Linux should have deleted the DB in /tmp .. I guess you haven't rebooted since you have more services on your server ..  please continue to monitor this 👍 .. I will close the issue now. If errors occur again, please comment here. We can then reopen the issue.

**Comment by un99known99** [comment]
@return42 I do have a real time monitoring set on the log file - so far it runs fine - thanks for fixing!

**Comment by un99known99** [comment]
@return42 I still do have database locked errors, is this normal behaviour?
Size looks ok?

rw-r--r-- 1 searxng searxng 69632 Jul  9 07:48 sxng_cache_DATA_CACHE.db
-rw-r--r-- 1 searxng searxng 61440 Jul  9 07:51 sxng_cache_ENGINES_CACHE.db



2025-07-09 07:47:38,971 ERROR:searx: call to ResultContainer.add_timing after ResultContainer.close
164 2025-07-09 07:47:42,394 ERROR:searx.plugins.tracker_url_remover: Exception while calling on_result
165 Traceback (most recent call last):
166   File "/usr/local/searxng/searxng-src/searx/plugins/_core.py", line 270, in on_result
167     ret = bool(plugin.on_result(request=request, search=search, result=result))
168                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
169   File "/usr/local/searxng/searxng-src/searx/plugins/tracker_url_remover.py", line 42, in on_result
170     result.filter_urls(self.filter_url_field)
171   File "/usr/local/searxng/searxng-src/searx/result_types/_base.py", line 292, in filter_urls
172     _filter_urls(self, filter_func=filter_func)
173   File "/usr/local/searxng/searxng-src/searx/result_types/_base.py", line 127, in _filter_urls
174     new_url = filter_func(result, field_name, url_src)
175               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
176   File "/usr/local/searxng/searxng-src/searx/plugins/tracker_url_remover.py", line 54, in filter_url_field
177     return TRACKER_PATTERNS.clean_url(url=url_src)
178            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
179   File "/usr/local/searxng/searxng-src/searx/data/tracker_patterns.py", line 101, in clean_url
180     for rule in self.rules():
181   File "/usr/local/searxng/searxng-src/searx/data/tracker_patterns.py", line 68, in rules
182     self.init()
183   File "/usr/local/searxng/searxng-src/searx/data/tracker_patterns.py", line 45, in init
184     self.load()
185   File "/usr/local/searxng/searxng-src/searx/data/tracker_patterns.py", line 54, in load
186     self.add(rule)
187   File "/usr/local/searxng/searxng-src/searx/data/tracker_patterns.py", line 57, in add
188     self.cache.set(
189   File "/usr/local/searxng/searxng-src/searx/cache.py", line 369, in set
190     self.DB.execute(sql, (key, value, expire, value, expire))
191 sqlite3.OperationalError: database is locked

**Comment by inetol** [comment]
> I still do have database locked errors, is this normal behaviour? Size looks ok?

See https://github.com/searxng/searxng/issues/4951
